### ISSUE TITLE
Lab 1 Feedback

### ISSUE THREAD

**Issue by alanarnholt** [STT3830-Fall2019/lab1-brittanymsh#1]
@brittanymsh

In the YAML put your name between the quotes where it says Your Name

The starter code has been changed so that the first footnote does not appear correct....the footnote should be

Lab^[The material in Section \@ref(lab) is modified from the Chapter 2 lab of [_An introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf).] {#lab} 

Extra numbering for  Matrix Command and multiple other commands...while not wrong it does mirror the sample document given.

Figure 1.1 needs to be hyperlinked and green...use something like the following:

To display the saved file as shown in Figure \@ref(fig:ig), use the `include_graphics()` function from `knitr`.^[Use the argument `dpi = 96` inside `include_graphics()`.] 

```{r, label = "ig", echo = FALSE, fig.cap = "Using `knitr::include_graphics()`"}
knitr::include_graphics("./JPG/YourFileName.jpeg", dpi = 96)

The References are both hardcoded and automatically created....please only automatically create this section...

**Comment by brittanymsh** [comment]
@alanarnholt The issues will be resolved

**Comment by alanarnholt** [comment]
@brittanymsh Please see me for help on line 171 (still a little off).   The references should be generated automatically...that is, you have them hardcoded.
